blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/Loony2392/ha_hacs_divera_247/issues/new?template=feature_request.yml
    about: Schlage eine neue Idee f√ºr die Integration vor