name: Test Divera 24/7 Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements_core_min.txt
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_core_min.txt --requirement requirements_test.txt
          scripts/install/frontend

      - name: â²ï¸ Set time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Europe/Berlin'

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: pytest --maxfail=1 --disable-warnings -q
